---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javaappcontainer
        image: somabr/java-web-app:20210819
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  selector:
    app: javawebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javaappdeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource

